In [1]:
import numpy as np
import networkx as nx

In [34]:
second_indices = []
excluded_indices=[]
base_index = 0
excluded_indices.append(base_index)
v=2
e=(v-1)*2
m_dis=v+e
q_dis=m_dis+v
def create_connected_graph(n):
    G = nx.path_graph(n)
    return G
def add_random_edge(G):
        nodes = list(G.nodes())
        n = len(nodes)
        max_edges = n * (n - 1) // 2  # Maximum number of edges in a complete graph

        if G.number_of_edges() == max_edges:
            print("Already a complete graph")
            return

        while True:
            u, v = np.random.choice(nodes, 2, replace=False)  # Randomly select two distinct nodes
            if not G.has_edge(u, v):  # Check if the edge does not already exist
                G.add_edge(u, v)  # Add the new edge to the graph
                break  # Exit the loop once a new edge is added
def increase_edge_connectivity(G, target_connectivity):
        """
        Increase the edge connectivity of the graph G to the target_connectivity.
        """
        current_connectivity = nx.edge_connectivity(G)
        
        while current_connectivity < target_connectivity:
            add_random_edge(G)
            current_connectivity = nx.edge_connectivity(G)  
graph=create_connected_graph(v) 
#while graph.number_of_edges() <= (v * (v - 1)) // 2:
#increase_edge_connectivity(graph, 3)
for i in range(v-1):
    neighbors_ex = sorted(graph.neighbors(i))
    base_index += len(neighbors_ex)+1
    excluded_indices.append(base_index)
first_indices = [i for i in np.arange(m_dis) if i not in excluded_indices]
node_to_index = {node: v + 2 * len(graph.edges) + idx for idx, node in enumerate(graph.nodes())}

for i in range(v):
    neighbors = sorted(graph.neighbors(i))
    # print(neighbors)
    for j in neighbors:
            # Update second_indices using the mapping
        second_indices.append(node_to_index[j])
# print(excluded_indices)
# print(first_indices)
# print(second_indices)
# Create pairs using broadcasting
pairs = np.transpose([first_indices, second_indices])
# print('pairs: \n',pairs)
# Initialize the kernel matrix M
M = np.zeros(( len(pairs), q_dis))
# Assign -1 and 1 to the corresponding places in M
for i, (idx1, idx2) in enumerate(pairs):
    M[i, idx1] = -1
    M[i, idx2] = 1
M_inv=np.linalg.inv(M@M.T)  
print('M:\n',M)
for i in range(M.shape[0]):
    print((M@M.T)[i,:])
print('M_inv',M_inv)
print('Inter:\n',M.T@M_inv@M)

M:
 [[ 0. -1.  0.  0.  0.  1.]
 [ 0.  0.  0. -1.  1.  0.]]
[2. 0.]
[0. 2.]
M_inv [[0.5 0. ]
 [0.  0.5]]
Inter:
 [[ 0.   0.   0.   0.   0.   0. ]
 [ 0.   0.5  0.   0.   0.  -0.5]
 [ 0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.5 -0.5  0. ]
 [ 0.   0.   0.  -0.5  0.5  0. ]
 [ 0.  -0.5  0.   0.   0.   0.5]]


In [ ]:
data = np.load('mfddata.npy')

# Assuming the data is in the form of two columns: [density, flow]
densities = data[:, 0]  # First column
flows = data[:, 1]      # Second column

# Create the scatter plot
plt.scatter(densities, flows, alpha=0.5, edgecolors='w', s=100)
plt.xlabel('Average Density (veh/km)')
plt.ylabel('Average Flow (veh/hr)')
plt.title('Macroscopic Fundamental Diagram (MFD)')
plt.grid(True)
plt.show()

In [12]:
pwd

'D:\\Thesis\\unjam\\power_unit'

In [ ]:
data = np.load('mfddata.npy')

# Assuming the data is in the form of two columns: [density, flow]
densities = data[:, 0]  # First column
flows = data[:, 1]      # Second column

# Create the scatter plot
plt.scatter(densities, flows, alpha=0.5, edgecolors='w', s=100)
plt.xlabel('Average Density (veh/km)')
plt.ylabel('Average Flow (veh/hr)')
plt.title('Macroscopic Fundamental Diagram (MFD)')
plt.grid(True)
plt.show()