In [1]:
import numpy as np

In [4]:
a=np.ones(8)
a[2:4]=4

In [6]:
a[0:2]=3
a[2:4]=4
a[4:6]=5
a

array([3., 3., 4., 4., 5., 5., 1., 1.])

In [9]:
def hankel_matrix_with_equal_off_diagonal(n, m, off_diagonal_value=0, diagonal_value=1):
    hankel = [[off_diagonal_value] * m for _ in range(n)]
    for i in range(n):
        for j in range(m):
            hankel[i][j] = diagonal_value if i + j == n - 1 else off_diagonal_value
    return hankel

# Example usage:
n = 4  # Number of rows
m = 5  # Number of columns
off_diagonal_value = 2  # Value for off-diagonal elements
diagonal_value = 1  # Value for diagonal elements
hankel = hankel_matrix_with_equal_off_diagonal(n, m, off_diagonal_value, diagonal_value)
print("Hankel Matrix:")
for row in hankel:
    print(row)

Hankel Matrix:
[2, 2, 2, 1, 2]
[2, 2, 1, 2, 2]
[2, 1, 2, 2, 2]
[1, 2, 2, 2, 2]


In [13]:
v1 = np.array([1, 2, 3]).reshape((-1, 1))
v2 = np.array([10, 20, 30]).reshape((-1, 1))
v3 = np.array([100, 200, 300]).reshape((-1, 1))
v4 = np.array([100.1, 200.1, 300.1]).reshape((-1, 1))
v5 = np.array([1.1, 2.2, 3.3]).reshape((-1, 1))

X = np.hstack((v1, v2, v3, v4, v5))
M = 5
d = 3

X_ = np.zeros((d * X.shape[0], X.shape[1]+1-d))
for i in range (d):
   X_[i*X.shape[0]:(i+1) * X.shape[0], :] = X[:X.shape[0], i:i+(X.shape[1]+1-d)]
                                              
print(X_)                                             

[[  1.   10.  100. ]
 [  2.   20.  200. ]
 [  3.   30.  300. ]
 [ 10.  100.  100.1]
 [ 20.  200.  200.1]
 [ 30.  300.  300.1]
 [100.  100.1   1.1]
 [200.  200.1   2.2]
 [300.  300.1   3.3]]
